### PR TITLE
adding magic.recommended and spell setting conveniences

### PR DESCRIPTION
**Pull request by timsgardner**
`alter-var-root` is horrible, and making the user have to remember which spells to use and call them just to enable basic and crucial optimizations doesn't make sense. Furthermore, as it stands the user must set the spells in just the right way - the right order, no repeats. This is onerous, error prone, and brittle, especially since every library using magic has to set these spells up independently without interfering with each other. Setting the default value of `*spells*` to enable intrinsics and var lifting would help (and we should probably do that), but the underlying problem will persist so long as `*spells*` is extensible.

I'm proposing some functions to mutate `*spells*` a bit more safely, and, secondarily, a function `magic.recommended/setup-spells!` that ensures important default values are in place; we could also just set those values to the default anyway, though it might take a bit of namespace juggling to avoid cyclic dependencies.

### CODE REVIEW

**Comment by timsgardner** [comment]
Another option would be to use a map with keys rather than a vector - easy to ensure idempotence. That would make any order-dependence of the spells trickier however.

**Comment by timsgardner** [comment]
On further reflection I'm starting to think dynamic variables are just the wrong way to configure magic. You can't even meaningfully use them with `binding`. Certainly a bare vector of transformation functions doesn't seem like the right interface to expose to consumers.

**Comment by nasser** [comment]
Compiler configuration is complicated, and figuring out how to do it in a sane, functional way is important.

> `alter-var-root` is horrible, and making the user have to remember which spells to use and call them just to enable basic and crucial optimizations doesn't make sense.
> ...
> You can't even meaningfully use them with binding

The way I use spells is

```clojure
(binding [magic/*spells* [intrinsics lift-vars]
          *unchecked-math* true
          *compile-path* "."]
  (compile 'some.namespace))
```

For AOT this is workable, because you're always at the very least binding `*compile-paths*` so there's an opportunity to bind `magic/*spells*` as well. Internally, magic is not driven by dynamic vars anywhere, and `*spells*` only serves to establish the initial symbolizers.

That said, none of this addresses the REPL use case. Is that what you're referring to?

> Furthermore, as it stands the user must set the spells in just the right way - the right order, no repeats. This is onerous, error prone, and brittle, especially since every library using magic has to set these spells up independently without interfering with each other.

Compiler passes are unavoidably order-dependent, but libraries shouldn't be specifying their own spells. Compiler configuration typically happens as a last step before lower level code is generated and happen in one place. In the same way that a C# library does not specify what optimizations to build it with, it does not make sense to me that a Clojure library could specify what magic spells to use.

Additionally, spells are not just optimizations. They allow different bytecode to implement the same Clojure semantics so that e.g. we can use a DLR spell for reflective call sites on desktop but use a different one for reflective call sites on iOS. A library can't know what platform it will be built for, so specifying its own spells does not make sense to me.

Can you describe the library use case further? 

> Setting the default value of *spells* to enable intrinsics and var lifting would help (and we should probably do that)

Agreed. This is ergonomics, though. See LLVM below.

> the underlying problem will persist so long as `*spells*` is extensible

The idea is that people can write their own spells as libraries, and not that libraries would specify their own spells to be compiled with. The extensibility is meant to avoid hardcoding optimizations and transformations into the compiler, and rather leaving it open to the ecosystem and end user if they wish to intervene.

> Another option would be to use a map with keys rather than a vector - easy to ensure idempotence. That would make any order-dependence of the spells trickier however. We could use a hashmap with a total order or something, but maybe that's too complicated.

Again, order dependance is unavoidable and tricky. `tools.analyzer`'s passes are [scheduled](https://github.com/nasser/magic/blob/master/magic/analyzer.clj#L237) using [metadata on vars](https://github.com/nasser/magic/blob/master/magic/analyzer/analyze_host_forms.clj#L37) . Something like this could be used for spells, but its not necessarily any simpler.

If you could describe how you're using magic and `*spells*` it would help. There are no ergonomics designed into the compiler yet, so I don't stand by the user experience in any way, but I want to make sure that the semantics are not foreclosing on any reasonable workflows.

---

For comparison, here is how `clang` does it.

```
$ clang program.c -o program
```

By default, the compiler performs no optimizations and will generate semantically correct but not stellar code. `program` is a runnable binary above. In practice, users will do the following

```
$ clang -O3 program.c -o program
```

`-O3` is the highest level of optimization, and this will generate code that is "as fast as C" as we understand that to mean. Internally, clang optimizes your code in [passes](http://llvm.org/docs/Passes.html), and (from [here](https://stackoverflow.com/questions/15548023/clang-optimization-levels)) `-O3` actually expands to

```
$ clang -targetlibinfo -tti -verify -globalopt -demanded-bits -branch-prob -inferattrs -ipsccp -dse -loop-simplify -scoped-noalias -barrier -adce -deadargelim -memdep -licm -globals-aa -rpo-functionattrs -basiccg -loop-idiom -forceattrs -mem2reg -simplifycfg -early-cse -instcombine -sccp -loop-unswitch -loop-vectorize -tailcallelim -functionattrs -loop-accesses -memcpyopt -loop-deletion -reassociate -strip-dead-prototypes -loops -basicaa -correlated-propagation -lcssa -domtree -aa -block-freq -float2int -lower-expect -sroa -loop-unroll -alignment-from-assumptions -lazy-value-info -prune-eh -jump-threading -loop-rotate -indvars -bdce -scalar-evolution -tbaa -assumption-cache-tracker -momit-leaf-frame-pointer -elim-avail-extern -mldst-motion -slp-vectorizer -gvn -inline -globaldce -constmerge -vectorize-loops -vectorize-slp -argpromotion program.c -o program
```

Most of the optimization is done by `opt`, the LLVM optimizer, and per [their documentation](http://llvm.org/docs/CommandGuide/opt.html)

> The order in which the options occur on the command line are the order in which they are executed (within pass constraints).

My understanding of [pass constraints](http://llvm.org/docs/WritingAnLLVMPass.html#introduction-what-is-a-pass) are that they group passes by the area of code they target but not a whole lot more.

So

1. Clang ships with a large number of optimization passes
2. It does almost none of them by default
3. They are order dependent
4. In theory, you could specify the ones you want
5. In practice, you use a curated set that also ships with the compiler
6. Writing a new optimization pass is doable, but very far from the normal user experience

I think magic should ship with a large number of useful spells. Not performing any transformations by default is important because it keeps the compiler core from becoming intractably complicated with conditional logic, and putting transformations into passes keeps the architecture flexible. A curated list of "the best ones" is also a great idea and magic should ship with that, but ideally people could also pull new spells off of the package manager or write their own.

**Comment by timsgardner** [comment]
It makes sense to learn form other compilers, but magic is in many ways a fundamentally different thing. I buy that the standard practice in compilers is to express optimization passes as command-line flags, but the standard practice is also to compile whole programs at a time, statically, from outside, wiping the entire environment each time, with the compiler itself essentially inaccessible from code, and the code not partaking of a dynamic runtime, and nothing remotely approaching live programming, and the people supplying the compiler options being either compiler experts, or IDEs rather than people at all.  Whereas magic is, or could be, a pliant, modular, interactive, fully dynamic metaprogramming tool, that must be capable of seamless integration into non-magic codebases, files, even forms. The ability to gracefully use it from the REPL and from libraries is not just nice, it's essential, and we should hold it to at least the same standard of composability and hygiene that we hold macro libraries to; probably more, since it's such a powerful tool.

Spells are either part of the user-facing interface or not. If we expect them to be supplied as libraries, they're part of the user-facing interface, and we should put a lot of thought into the api for specifying them. It's totally plausible and desirable that some user code assumes certain spells are in place. What is to be gained by discouraging that, or making it an additional and increasingly complicated burden on the user (eg, "to use this library make sure you run spells [x y z]"), if we can find a way of cleanly automating it? We are under no obligation to replicate the shortcomings of existing compilers.

The default spells aren't just a matter of ergonomics (vitally important as those are!). One strong option is to consider `*spells*` an internal variable rather than a user-facing interface until we get a better idea of how to tackle extensibility, and just set it to the defaults of [intrinsics lift-vars] for now. Then we could punt on how to make magic properly extensible for a bit while we think about various strategies.

The longer we wait to do this, though, the more code is going to get written that digs around inside `*spells*` and calls `alter-var-root` in various weird ways (needs to ensure idempotence, needs some story for preserving order, etc etc), with strong assumptions about the structure of that variable. That means we'll be bogging the community down with more and more half-assed library-specific non-composable approaches to modularizing spells, and any future revision of the `*spells*` interface will be a drastically breaking change.

I *mostly* use magic from the repl. I *rarely* call `(binding [...] (compile...))`. Trying to figure out whether I've remembered to set the right spells is already awful, and library-supplied spells will make that a nightmare. We need to do better than `*unchecked-math*`, and way better than clang.

So, for now, I strongly think we should make `*spells*` a private variable and load it up with `intrinsics` and `lift-vars` until we have a better sense of what the ultimate interface should be. This is going to determine the whole flavor of magic.

**Pull request closed without merging**
